javascript_compressor: closure
css_compressor:        sass
template_function:     dc._.template
embed_assets:          datauri
gzip_assets:           off

javascripts:
  note_embed:
    - src/js/vendor/underscore/underscore.js
    - src/js/note_embed.js
    - src/templates/*.jst

stylesheets:
  note_embed:
    - src/css/*.scss
